[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink

platform_packages =
    tool-openocd@3.1200.0

monitor_speed = 115200
monitor_echo = no
monitor_eol = LF

; Pin the BNO085 SH-2 host library to the version used by the firmware transport.
lib_deps =
    https://github.com/ceva-dsp/sh2.git#37e6f23
