; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink

platform_packages =
    tool-openocd@3.1200.0

monitor_speed = 115200
monitor_echo = no
monitor_eol = LF

lib_deps =
    https://github.com/ceva-dsp/sh2.git#37e6f23